### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by Ashllives** [wwcodemanila/WWCodeManila-Python#1]

**Comment by Ashllives** [comment]
https://github.com/Ashllives/wwcode-loops/blob/master/loops_CGSevilla.py

**Comment by trizzy-orozco13** [comment]
https://github.com/trizzy-orozco13/codinger/blob/master/exercises01_TrizzyOrozco.py

**Comment by neequole** [comment]
We can remove comparison with `True` as the function will already evaluate to True
```python
#if is_coins(cash) == True:
if is_coins(cash):
    paper_bills.append(cash)
```

* The `is_coins` was already fix to return False for amount > 10 :)
