### ISSUE TITLE
Chelsea Lim - Exercise01

### ISSUE THREAD

**Issue by ChelseaVanessaLim** [wwcodemanila/WWCodeManila-Python#10]
https://github.com/ChelseaVanessaLim/wwc-python/blob/master/cclim_exercise01.py

**Comment by neequole** [comment]
* Question from member: How can format to two decimal places?
* Answer: Can use ".2f" - print("Hi! Your change is %2f', %change) or print("Hi! Your change is {:.2f}'.format(change))
