### ISSUE TITLE
Chelsea Lim

### ISSUE THREAD

**Issue by ChelseaVanessaLim** [wwcodemanila/WWCodeManila-Python#12]
https://github.com/ChelseaVanessaLim/wwc-python/blob/master/cclim_exercise02.py

**Comment by neequole** [comment]
* Nice! You have given us a different approach on how to solve this problem - splitting the string to array
`elements = text.split()`
* Aside from using array, we can also utilize string indexing to get the reward no. and name
`name = text[1:-1].strip()`
* We can fix the wrong reward `#0` below
```shell
>> Please enter text: 1 nicole i tibay f
>> Hi Nicole I Tibay! You have successfully redeem reward #0 - Coke sakto! Thank you for choosing Aling Nena's sari-sari store.
```
by
```python
# reward_index = int(elements[0])-1
# reward = rewards[reward_index]
reward_index = int(elements[0])
reward = rewards[reward_index-1]
```
