### ISSUE TITLE
Functions 01

### ISSUE THREAD

**Issue by samuel012** [wwcodemanila/WWCodeManila-Python#15]
https://github.com/samuel012/python_exercises/blob/master/functions01.py

**Comment by neequole** [comment]
* Minor revision:
As per last presentation, we can already remove the loop here
`', '.join(str(e) for e in list(PHP_EXCHANGE_RATE.keys()))` -> `', '.join(list(PHP_EXCHANGE_RATE.keys()))`

* Good job especially utilizing `lower()` for handling inputs :)
