### ISSUE TITLE
Elissa Cabal - exercise 01

### ISSUE THREAD

**Issue by ghost** [wwcodemanila/WWCodeManila-Python#16]
https://github.com/Elissa-Cabal/wwcpython/blob/master/ehcabal_exercise01.py

**Comment by neequole** [comment]
Just some minor revisions in line with [PEP8](https://www.python.org/dev/peps/pep-0008/) :)
```python
x = input('How much is your bill? ')
y = input('How much is your payment? ')
```

We can rename these variables to e.g. `total_bill_amount`, `payment_amount`  for easy understanding of what it is for. Good job!
