### ISSUE TITLE
cgsevilla_dictionary

### ISSUE THREAD

**Issue by Ashllives** [wwcodemanila/WWCodeManila-Python#18]
https://github.com/Ashllives/python_dictionary/blob/master/cgsevilla_dictionary01.py

**Comment by maryletteroa** [comment]
Hello, Cecille.

- Line 57-58: You might want to check if the item exists in the `products `dictionary first before putting the item inside the `cart` dictionary. You can also catch void items this way (void items = those not in products dictionary. For example

```
if item in products:
    if item not in cart:
        # add to cart
        # increment
    else:
        # increment
else:
    # declare void

```
- Line 65: You can  remove the if statement here, and just put the rest of the code outside the while loop. This means that the code will only run if the while statement is false; that is if `is_done `is any character other than y

- Line 69: `cart[key]` is the same as `value`

- Line 70: You can also use string formatting so the line is more readable.

That's it.

Thank you. And keep at it :)

**Comment by Ashllives** [comment]
Hello Ms Marylette,

Thank you for proof reading my codes. Uhm is it called proof reading? :)
Anyway, I'll have a look at it again and rewrite it po.

Cheers,

Cecille
