### ISSUE TITLE
Cecille Sevilla - Classes

### ISSUE THREAD

**Issue by Ashllives** [wwcodemanila/WWCodeManila-Python#31]
https://github.com/Ashllives/ww_code_my_activities/blob/master/basics/cgsevilla_class.py

**Comment by neequole** [comment]
Hello Cecille,

Congratulations on finishing the basic concepts of programming using Python!

Just a few points for your class exercise:

* You can skip using `self.get_x()` and `self.get_y()` and access directly the `self.x` and `self.y`

```python
    def __str__(self):
        return "Rocket is moving in %dx and %dy directions." %(self.x, self.y)
        # return "Rocket is moving in %dx and %dy directions." %(self.get_x(), self.get_y())
```

* Rename function `move_up` to `move` or `move_rocket` as you also move it in horizontal direction.
* You can use [list comprehension](http://treyhunner.com/2015/12/python-list-comprehensions-now-in-color/) for the ff and also skip passing 0 in your x and y as it is already defaulted to 0.

```python
# create a fleet of rockets
# rocket_fleet = []
# for num in range(5):
#     rocket_fleet.append(Rocket(x = 0, y = 0))

rocket_fleet = [Rocket() for num in range(5)]
```

* You can take advantage of list slicing to skip looping through some of your rockets :)

```python
# compute distances between the rockets in my fleet
# distance = 0
# for index1, rocket_x in enumerate(rocket_fleet):
#     for index2, rocket_y in enumerate(rocket_fleet):
#         if index2 <= index1:
#             pass
for index1, rocket_x in enumerate(rocket_fleet):
    for index2, rocket_y in enumerate(rocket_fleet[index1+1:]):
          distance = rocket_x.get_distance(rocket_y)
```
