### ISSUE TITLE
Patricia Ilano - Exercise 2

### ISSUE THREAD

**Issue by ilanopat** [wwcodemanila/WWCodeManila-Python#35]
https://github.com/ilanopat/wwcode-exercises/blob/master/exercises02-pat.py

**Comment by neequole** [comment]
Hi Patricia!

Good job on using negative index for parsing out the input string! Also, thank you for sharing your code in front and through that we learned from you that `"""..."""` can be used for print statement!

```python
print(f"""Hi {name}! You have successfully redeem reward #{rewardnum} - {rewardname}! Thank you for choosing Aling Nena’s Sari-sari store.""")
```

Hope you enjoyed the session and see you on upcoming ones :)
