### ISSUE TITLE
Gaia - Exercise 01

### ISSUE THREAD

**Issue by gaiaroyeca** [wwcodemanila/WWCodeManila-Python#49]
Hi, you can view my input via this link: [TinderaBot](https://github.com/gaiaroyeca/TinderaBot/blob/master/exercises01.py)

**Comment by neequole** [comment]
Hi Gaia, good job! You were able to use the float() statement which is the main twist on the exercise - given that the input() will store the input as a string and also the need to capture cases where bills can have centavos :)

Thumbs up on naming the variables in a verbose way but no need to shortcut, e.g. `tot_change` can be named `total_change`

**Comment by gaiaroyeca** [comment]
Yay!
