### ISSUE TITLE
Frances - Challenge 2: String Manipulation

### ISSUE THREAD

**Issue by fran-ces-m** [wwcodemanila/WWCodeManila-Python#91]
https://github.com/francesmjcx/wwcode-python/blob/master/stringchallenge.py

**Comment by alyssonalvaran** [comment]
Cool! I like how you used `title()` on the customer's name to make sure that the first letter of each word is capitalized. It would be good though, if you can display the list of items first. ;)

Anyway, congrats on completing this challenge!
