### ISSUE TITLE
Sermil - Rewards Challenge

### ISSUE THREAD

**Issue by smatoto** [wwcodemanila/WWCodeManila-Python#93]
https://github.com/smatoto/wwcode-python/blob/master/rewards-challenge.py

**Comment by alyssonalvaran** [comment]
Nice job! It's cool how you approached the problem by using `split()`. This would assume though that the user will enter exactly 3 words for his/her name. Some areas for improvement would be:
1. Displaying the list of rewards first
2. Getting the first and last characters only as the reward and the gender respectively and assuming that everything in between would be the name.

Congratulations on completing this challenge! :)
